version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tullo-postgres
    environment:
      POSTGRES_USER: tullo
      POSTGRES_PASSWORD: tullo_password
      POSTGRES_DB: tullo_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tullo"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tullo-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tullo-backend
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=tullo
      - DB_PASSWORD=tullo_password
      - DB_NAME=tullo_db
      - DB_SSLMODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - JWT_EXPIRY_HOURS=168
      - RATE_LIMIT_MESSAGES_PER_SECOND=10
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
